---
name: Build

on:
  push:
    branches: [master]
    paths:
      - 'ext/**'
      - 'lib/**'
      - 'test/**'
      - '*.gemspec'
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.7', '3.1']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rake
