---
name: Cross Compile

on:
  push:
    tags:
      - "v*"

jobs:
  ci-data:
    name: Fetch CI data
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.fetch.outputs.result }}
    steps:
      - uses: oxidize-rb/actions/fetch-ci-data@v1
        id: fetch
        with:
          supported-ruby-platforms: true
          stable-ruby-versions: |
            exclude: [head]
  cross-gem:
    name: Compile native gem for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    needs: ci-data
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJSON(needs.ci-data.outputs.result).supported-ruby-platforms }}
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - uses: oxidize-rb/actions/cross-gem@v1
        id: cross-gem
        with:
          platform: ${{ matrix.platform }}
          ruby-versions: 2.6,2.7,${{ join(fromJSON(needs.ci-data.outputs.result).stable-ruby-versions) }}

      - uses: actions/upload-artifact@v4
        with:
          name: colordom-${{ matrix.platform }}
          path: ${{ steps.cross-gem.outputs.gem-path }}
  merge-artifacts:
    runs-on: ubuntu-latest
    needs: cross-gem
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: cross-gem
          pattern: colordom-*
